### ISSUE TITLE
errors launching app

### ISSUE THREAD

**Issue by meghalithic** [futres/RShinyFuTRES#3]
In the branch mab-testing, I put both the .R files into the pyConvApp file, launched RShiny on a new RStudio session, loaded the "example.csv" and got this error: 

```
Listening on http://127.0.0.1:3463
Warning: Error in open_df: could not find function "open_df"
  96: renderTable [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#171]
  95: func
  82: renderFunc
  81: output$contents
   1: shiny::runApp
Warning: Error in open_df: could not find function "open_df"
  96: renderTable [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#184]
  95: func
  82: renderFunc
  81: output$clean_data
   1: shiny::runApp
Warning: Error in open_df: could not find function "open_df"
  44: <observer> [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#254]
   1: shiny::runApp
Warning: Error in open_df: could not find function "open_df"
  99: renderPrint [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#273]
  98: func
  82: renderFunc
  81: output$text
   1: shiny::runApp
```

This is different from the errors @prasiddhigyawali got when the other .R files were outside the pyConvApp folder (error was py_resolve_dots() not found, as well as <Annonymos> and <eval>) or when just the data_cleaning.R file was in the pyConvApp folder (error was <Annonymous> and <eval>).

**Comment by meghalithic** [comment]
I just got this error when only the data_cleaning.R was in the pyConvApp folder:

```
Listening on http://127.0.0.1:3463
Warning: Error in open_df: could not find function "open_df"
  96: renderTable [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#171]
  95: func
  82: renderFunc
  81: output$contents
   1: runApp
Warning: Error in open_df: could not find function "open_df"
  96: renderTable [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#184]
  95: func
  82: renderFunc
  81: output$clean_data
   1: runApp
Warning: Error in open_df: could not find function "open_df"
  44: <observer> [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#254]
   1: runApp
Warning: Error in open_df: could not find function "open_df"
  99: renderPrint [/Users/meghanabalk/GitHub/futres/RShinyFuTRES/pyConvApp/app.R#273]
  98: func
  82: renderFunc
  81: output$text
   1: runApp
```

**Comment by meghalithic** [comment]
And the same error without either .R files in the pyConvApp folder.

Perhaps there is a dependency I'm missing?

**Comment by nsewnath** [comment]
So open_df is a python function within the data_cleaning.py file. The python file needs to be imported as a module before it can be used. 

So we can look at something like this: https://rstudio.github.io/reticulate/articles/calling_python.html (the import module section) 

So we would do something like 

data_clean <- import ("data_cleaning") #similarly to how you would import a custom py script within another py script. 
data_clean$open_df("your directory")

@prasiddhigyawali does this make sense to you? Adding this makes the custom py functions accessible in the script.
