### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by meghalithic** [futres/RShinyFuTRES#4]
May need to make a yaml file to create environment to include:
- r packages
- python version
- numpy version
- pandas version

**Comment by nsewnath** [comment]
Environmental file added to repo. We can add dependencies as we go. 

To create the condo environment use command in terminal:
` conda env create --file environment.yml `

To activate environment: 
`conda activate rshiny_futres_env`

To deactivate environement: 
`conda deactivate`
